# -- TRAIN
dataset_path: "datasets/arxiv-metadata-oai-snapshot.json"
transformer_model: "base" # will be used later on for testing in KeyBERT
n_keywords: 10
ngrams:
    - 1
    - 1
use_mmr: false
use_msd: false
num_workers: 20
model_name: "all-MiniLM-L6-v2" # default KeyBERT model

# -- INTERMEDIATE
save_path: logs/pagerank_100

# QUERY
keywords:
    - hubble
    - telescope
papers:
    - paper_path_1
    - paper_path_2
    # OR
    - directory_with_papers_1
    - dir_with_papers_2
